### ISSUE TITLE
Crear vista de administración de servicios por usuario

### ISSUE THREAD

**Issue by sebablasko** [niclabs/KippZonen-ServiceMode-Server#3]
Vista que permita configurar: 
 - Periodicidad de mails con datos recolectados e intervalo de datos a enviar en cada situación
 - Contraseña de acceso al sistema

**Comment by JoseTapiaG** [comment]
138221cf5f7ad3837958e245f914a783fc3f91d6
21cabc0342f569360087e028b9dc45517b8769f2
3414486504ea5653a7c8e114c860ccade2985acd
